export default [
	"ngủm",
	"chết",
	"tắt thở",
	"ra đi",
	"ngỏm củ tỏi",
	"bị bruh",
	"dead",
	"về với ông bà",
	"lên thiên đàng",
	"chết trong lòng",
	"bay màu",
	"bị ung thư",
	"bị xi đa",
	"từ trần",
	"đi củi",
	"quy tiên",
	"quy ẩn giang hồ",
	"về với núi ngàn",
	"thả hồn theo gió",
	"chán cơm thèm đất",
	"ưa nghe kèn trống",
	"lên bàn thờ ngồi",
	"làm biếng thở",
	"nhăn răng",
	"băng hà",
	"khuất bóng",
	"dựa cột",
	"đi bán muối",
	"đu lên vách",
	"ngồi trên nóc ăn cơm 4 bữa",
	"ngủ với giun",
	"đi về nơi xa",
	"đứt bóng",
	"ngồi sau nải chuối uống rượu đào",
	"ngồi sau nải chuối ngắm gà khỏa thân",
	"xanh cỏ",
	"đi theo Marx–Lenin",
	"hết nợ đời",
	"giũ bụi trần",
	"thăng thiên",
	"viêm tịch",
	"rớt mạng",
	"đắp chiếu",
	"trùm mền",
	"xuống suối vàng",
	"nhắm mắt xuôi ta",
	"đi tàu sáu tấm",
	"đi tong",
	"tử vì đạo, chết vì quê hương",
	"thác vào âm ty",
	"chán cơm thèm nhang",
	"chơi với dế"
]
